### ISSUE TITLE
Implement logarithmic/linear toggle for the chart

### ISSUE THREAD

**Issue by trekhleb** [trekhleb/covid-19#14]

**Comment by JayJayBinks** [comment]
I created a pull request for this
https://github.com/trekhleb/covid-19/pull/15

**Comment by trekhleb** [comment]
Thanks for the fix, @JayJayBinks. It is live now.

**Comment by phedders** [comment]
I could be wrong but I think the log drawing is broken...
Looking at the UK the log graph is showing more deaths than recovered. But perhaps I have just misunderstood what it is showing.
