### ISSUE TITLE
Include Recovered in Chart/Table rows.

### ISSUE THREAD

**Issue by web-sys1** [trekhleb/covid-19#17]

**Comment by trekhleb** [comment]
Data about recovered people were missing in the [data-source](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series) before. Now it is available (with some regions that are missing, i.e. for Canada). But this data is now available on the [dashboard](https://trekhleb.github.io/covid-19/).
