### ISSUE TITLE
Implement "Reset country selection" functionality

### ISSUE THREAD

**Issue by trekhleb** [trekhleb/covid-19#2]

**Comment by sogyals429** [comment]
Hi @trekhleb 
I was working on this issue. Could you please help me with where the code for the searchbox was implemented. Was planning to add a button next it to for reset.
Thanks

**Comment by trekhleb** [comment]
Hi @sogyals429, thanks for your suggestion and help!
This issue us fixed already in https://github.com/trekhleb/covid-19/commit/4673212e03775bea0774e52a1731480db01f65dd
