### ISSUE TITLE
Per capita, for each metric

### ISSUE THREAD

**Issue by kylegrover** [trekhleb/covid-19#31]
Since we're comparing countries of vastly different sizes, per capita figures can be much more informative. By pulling the population data [from the UN](https://population.un.org/wpp/Download/Standard/Population/) or elsewhere we could provide:
- confirmed per capita per country
- recovered per capita per country
- deaths per capita per country
- and perhaps active cases per capita per country

**Comment by kylegrover** [comment]
oops this might be a duplicate of #23

**Comment by trekhleb** [comment]
Closing this one in favour of https://github.com/trekhleb/covid-19/issues/23
