### ISSUE TITLE
unescaped user input

### ISSUE THREAD

**Issue by kylegrover** [trekhleb/covid-19#33]
typing ie `/` or `+` into the 'Search country' field crashes the app
problem occurs @ index.js:372 `new RegExp(countrySearchQuery.trim(), 'i')`

**Comment by kylegrover** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions
suggests this code
```
function escapeRegExp(string){
  return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); // $& means the whole matched string
}
```

**Comment by trekhleb** [comment]
Very good point! Thanks @kylegrover. It should be fixed now.
