### ISSUE TITLE
mortality miss-concept

### ISSUE THREAD

**Issue by hugosoftdev** [trekhleb/covid-19#37]
First of all, congratulations for the dashboard, I really liked it!

There is a problem that I noticed and that has been very common in the covid-19 dashboards, a misinterpretation of the concept of mortality. Mortality is a measure of the number of deaths (usually or due to a specific cause) in a population scaled to the size of that population per unit of time. The correct name of the metric being represented by this dashboard is lethality.

**Comment by trekhleb** [comment]
Thanks for correcting that @hugosoftdev! It is merged now.
