### ISSUE TITLE
Different graph colors for countries

### ISSUE THREAD

**Issue by moppman** [trekhleb/covid-19#5]
First, thanks for this, this is very useful.
The graphs for "confirmed", "deaths" and "recovered" are always yellow, red and green. This gets a bit confusing once you want to compare several countries.
I'm sure you've thought about this problem already. Maybe generate different shadings per country?
Thank you for considering!

**Comment by rafalgrm** [comment]
Probably sth like this? https://github.com/trekhleb/covid-19/pull/8 But maybe more contrasting colors...

**Comment by moppman** [comment]
Awesome, thanks!
